### PR TITLE
Update asiobass for OBS v27

### PR DESCRIPTION
**Pull request by foxx1337**
asiobass is the only stable, crackle-free and latency-free way of getting sound out of Rocksmith 2014, through ReaRoute into Reaper, then into OBS (and maybe into a virtual cable type of audio device to use as microphone for other software, plus OBS' virtual camera device).

### CODE REVIEW

**Comment by foxx1337** [comment]
I fully describe this setup on the [big lastpixel.tv article](https://lastpixel.tv/low-latency-rocksmith-obs-streaming-with-software-effects/#streaming-with-obs) I wrote about streaming / recording Rocksmith 2014.

**Comment by foxx1337** [comment]
As a note, while better, Juce is still not fully functional with Rocksmith 2014 through Reaper's ReaRoute. Circa 2020 it wouldn't work at all once a Juce client would connect at the other end of ReaRoute.

**Comment by Andersama** [comment]
You've got additional files thrown in the pr, be sure to clean those out, eg the cmake cache files etc.

**Comment by foxx1337** [comment]
Zoinks.

**Comment by Andersama** [comment]
By the way, (after looking at your article) you might want to check the voicemeeter plugin I wrote. ASIO's essentially a long standing mess of poorly written drivers etc. Since it seems like you're using voicemeeter in your setup, you might have better luck with the apis they provided to grab their audio buffers.

I will say though I have issues with voicemeeter, namely crackly audio....maybe you'll have better luck.

**Comment by foxx1337** [comment]
Hey, thanks - never checked it and I saw it among your repos!

I was just using Voicemeeter as an example. In my daily setup I just use guitar - interface - Reaper (ASIO) - Rocksmith (rs-asio through ReaRoute) - Reaper (ReaRoute) - OBS (obs-asio, and it's good for recording, streaming, etc) - in OBS, for the ASIO and the other audio sources: "monitor and output" into Line 1 (from Muzychenko's Virtual Audio Cable). Skype, Discord, etc use Line 1 as the microphone source then.

**Comment by Andersama** [comment]
@foxx1337 apparently you're not the only one w/ this issue for this setup, seems like there's likely an issue w/ rocksmith given voicemeeter's at least somewhat stable?

**Comment by Andersama** [comment]
Not sure because I didn't look at the combined edits, it seems like one of us might've mixed frees and deletes together, and that's no good.

**Comment by Andersama** [comment]
Ok, not sure about the other commits, but the ones for freeing and deleting I'll add in, that was definitely a goof on my part, probably should just use std::string instead. I'd skip on the unique_ptr one in the audio thread that's not really needed.

**Comment by Andersama** [comment]
I'm not sure that I'm going to take pr's against the bass asio version because people have to build this themselves anyway.

**Pull request closed without merging**
